#!/bin/sh

set -e

cd -P "$(dirname "$0")"
CHECK_ROOT="$PWD"
cd "$OLDPWD"

if [ "$#" -eq 0 ]; then
  exec find "$CHECK_ROOT/cases" -type f -name '*.sh' -exec "$0" -- {} +
elif [ "$1" = "--" ]; then
  shift
fi

export TMPDIR="${TMPDIR:-/tmp}"
CHECK_TMP="${TMPDIR%/}/check.$$"
CHECK_TAP="$CHECK_TMP/tap"
CHECK_STDOUT="$CHECK_TMP/stdout"

for arg; do
  if ! [ -r "$arg" ]; then
    echo "error: $arg: No such file or directory" >&2
    exit 2
  fi
done

trap 'rm -fr "$CHECK_TMP"' EXIT
mkdir "$CHECK_TMP"
mkfifo "$CHECK_TAP"
exec 3<>"$CHECK_TAP"
cat "$CHECK_TAP" &

check() {
  ( trap "report $1" EXIT
    CHECK_CASE="$2"
    CHECK_PWD="$PWD"
    cd "$CHECK_ROOT"
    . "$CHECK_ROOT/lib.sh"
    . "$CHECK_CASE"
  ) 1>"$CHECK_STDOUT" 3>&-
}

report() {
  status=$?
  title="${CHECK_CASE#"$CHECK_PWD/"}"
  if [ $status -eq 0 ]; then
    echo "ok $1 $title"
  else
    echo "not ok $1 $title"
    sed -e 's/^/# /' "$CHECK_STDOUT"
  fi
} >>"$CHECK_TAP"

index=1
failed=0
echo "1..$#" >&3

for arg; do
  check "$index" "$arg" || failed=1
  index=$((index+1))
done

[ $failed -eq 0 ] || exit 1
